# ---------------------------------------------------------
# STEP 1: Import the required libraries
# dotenv  -> Loads secret information like API keys
# streamlit -> Helps us create the web application
# os -> Helps us access environment variables
# genai -> Connects our application with Google Gemini AI
# PIL -> Helps us work with images
# ---------------------------------------------------------

from dotenv import load_dotenv
import streamlit as st
import os
import google.generativeai as genai
from PIL import Image


# ---------------------------------------------------------
# STEP 2: Load environment variables
# This loads variables stored inside our .env file.
# Our GOOGLE_API_KEY is stored there for security.
# ---------------------------------------------------------

load_dotenv()


# ---------------------------------------------------------
# STEP 3: Connect our application with Google Gemini
# os.getenv() reads the GOOGLE_API_KEY from the .env file.
# Think of the API key as a password/access key for Gemini.
# ---------------------------------------------------------

# gkey = "AIzaSyDB317nRioshbfTnfAsxyQS2vrEcG1Xf_Y"
genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))
# genai.configure(api_key=gkey)


# ---------------------------------------------------------
# STEP 4: Create a function to communicate with Gemini AI
#
# A function is simply a reusable block of code.
#
# This function receives:
# 1. Our main instruction/prompt
# 2. The uploaded food image
# 3. Additional input from the user
#
# Gemini analyzes all of these and gives us a response.
# ---------------------------------------------------------

def get_gemini_repsonse(input, image, prompt):

    # Select the Gemini AI model that we want to use
    model = genai.GenerativeModel("gemini-3.5-flash")

    # Send our prompt + image + user input to Gemini
    response = model.generate_content([input, image[0], prompt])

    # Return only the text generated by Gemini
    return response.text


# ---------------------------------------------------------
# STEP 5: Prepare the uploaded image for Gemini
#
# The user uploads a normal JPG/PNG image.
# We need to convert that image into data that Gemini
# can understand and process.
# ---------------------------------------------------------

def input_image_setup(uploaded_file):

    # Check whether the user has uploaded a file
    if uploaded_file is not None:

        # Convert the uploaded image into bytes
        # Bytes are a computer-readable form of the image.
        bytes_data = uploaded_file.getvalue()

        # Prepare the image information for Gemini
        # mime_type tells Gemini what type of image it is.
        # data contains the actual image information.
        image_parts = [
            {
                "mime_type": uploaded_file.type,
                "data": bytes_data
            }
        ]

        # Return the prepared image
        return image_parts

    else:

        # If the user has not uploaded an image,
        # show an error.
        raise FileNotFoundError("No file uploaded")


# ---------------------------------------------------------
# STEP 6: Start creating our Streamlit Web Application
# ---------------------------------------------------------

st.set_page_config(
    page_title="Personalized AI Calorie Counting App"
)


# ---------------------------------------------------------
# STEP 7: Display the main heading of our application
# ---------------------------------------------------------

st.header("Personalized AI Calorie Counter App")


# ---------------------------------------------------------
# STEP 8: Create a text input box
# ---------------------------------------------------------

user_prompt = st.text_input(
    "Input Prompt: ",
    key="input"
)


# ---------------------------------------------------------
# STEP 9: Create an Image Upload option
# ---------------------------------------------------------

uploaded_file = st.file_uploader(
    "Choose an image...",
    type=["jpg", "jpeg", "png"]
)


# ---------------------------------------------------------
# STEP 10: Display the uploaded image on the screen
# ---------------------------------------------------------

image = ""

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(
        image,
        caption="Uploaded Image.",
        use_container_width=True
    )


# ---------------------------------------------------------
# STEP 11: Create the Submit Button
# ---------------------------------------------------------

submit = st.button("Tell me the total calories")


# ---------------------------------------------------------
# STEP 12: Create the System Prompt / Instructions for AI
# ---------------------------------------------------------

input_prompt = """
You are an expert in nutritionist where you need to see
the food items from the image and calculate the total calories.

Also provide the details of every food item with calories
intake in the below format:

1. Item 1 - no of calories
2. Item 2 - no of calories
3. Item 3 - no of calories

Also provide the estimated total calories.
"""


# ---------------------------------------------------------
# STEP 13: Check whether the user clicked the button
# ---------------------------------------------------------

if submit:
    if uploaded_file is None:
        st.error("Please upload an image first.")
    else:
        image_data = input_image_setup(uploaded_file)

        response = get_gemini_repsonse(
            input_prompt,
            image_data,
            user_prompt
        )

        st.subheader("The Response is")
        st.write(response)

