app = "be10x-nutrition-calorie-app"
primary_region = "ams"

[processes]
  app = "python -m streamlit run app.py --server.port 8000 --server.address 0.0.0.0"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop_process"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']